### ISSUE TITLE
[Q] comparison with Snes9x "Reduce Slowdown" core option

### ISSUE THREAD

**Issue by eadmaster** [VitorVilela7/fastrom#1]
how does these hacks compare to the [Snes9x' "Reduce Slowdown" core option](https://docs.libretro.com/library/snes9x/#core-options)?

Are they more reliable/with less side-effects?

**Comment by VitorVilela7** [comment]
Hi eadmaster, the Snes9x's reduce slowdown option works by reducing the amount of master cycles per opcode. It's not a good option since it can spin-lock certain game operations such as SPC700 updates. It's preferred to use speed acceleration ROM hacks instead.
