### ISSUE TITLE
FastRom - Super Castlevania IV - Music cutoffs

### ISSUE THREAD

**Issue by Nekhbeth3000** [VitorVilela7/fastrom#2]
Issue: FastRom performance improvements seem to affect timings in game, by cutting music during level transitions.

Repro steps:
- Load SCIV FastRom.
- Play through a level and complete it
- The level transition map plays
- Notice the issue: the ending of the music track is cutoff instead of playing entirely
-  [optional] Compare with a vanilla SCIV rom 

Expected result: Music tracks play in their entirety

Current result: Music tracks are cut off

**Comment by thomasgoldstein** [comment]
While waiting for this bug to be fixed, maybe the known issues of each patch should be documented in this repo?

**Comment by VitorVilela7** [comment]
For clarification purpose, do you mean the music that is played during this section gets cutoff in particular?
![image](https://user-images.githubusercontent.com/12776674/148650117-08584b71-e3fd-440a-82d0-9e67ddc7d8c0.png)

I haven't noticed anything wrong after playing the first level carefully, so more details would be appreciated

**Comment by JaydeSix** [comment]
I'll second that it is working for me too, plays entire track and then fades out to next level.

**Comment by Nekhbeth3000** [comment]
I’ll try to repro in a couple weeks’ time, once I have access to my gear again. Note that I played the patched rom on an Analogue Super NT, so the hardware might be at fault?

**Comment by Nekhbeth3000** [comment]
> For clarification purpose, do you mean the music that is played during this section gets cutoff in particular? ![image](https://user-images.githubusercontent.com/12776674/148650117-08584b71-e3fd-440a-82d0-9e67ddc7d8c0.png)
> 
> I haven't noticed anything wrong after playing the first level carefully, so more details would be appreciated

-> Yes, I meant the music for the transition between levels

**Comment by VitorVilela7** [comment]
There is always a chance of that happening on the original too, so make sure to check which stage exactly causes the issue. A video would be good too.

**Comment by Nekhbeth3000** [comment]
Hi, I finally got to comparing both the retail and FastRom versions again. I can’t repro and both versions play the transition music the exact same way. To your point, Vitor, the issue I noticed last year could have been a freak occurrence that may be affecting the original too. 

Since it’s not a repro and is likely not due to the FastRom patch, I’ll close this issue.
